import { DEMO_LISTS_USER_ID, type RofList } from "@/lib/lists/types";

function ago(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

/** Sample lists for MVP until Supabase is connected. */
export const SAMPLE_LISTS: RofList[] = [
  {
    id: "list-grocery-1",
    userId: DEMO_LISTS_USER_ID,
    kind: "grocery",
    title: "Grocery list",
    createdAt: ago(48),
    updatedAt: ago(2),
    items: [
      {
        id: "gi-1",
        text: "Eggs",
        completed: false,
        reminderTime: "09:00",
        notes: "",
        createdAt: ago(48),
        updatedAt: ago(2),
      },
      {
        id: "gi-2",
        text: "Milk",
        completed: false,
        reminderTime: null,
        notes: "2%",
        createdAt: ago(48),
        updatedAt: ago(2),
      },
      {
        id: "gi-3",
        text: "Cheddar cheese",
        completed: false,
        reminderTime: null,
        notes: "",
        createdAt: ago(40),
        updatedAt: ago(40),
      },
      {
        id: "gi-4",
        text: "Bread",
        completed: true,
        reminderTime: null,
        notes: "",
        createdAt: ago(40),
        updatedAt: ago(5),
      },
      {
        id: "gi-5",
        text: "Butter",
        completed: false,
        reminderTime: null,
        notes: "",
        createdAt: ago(30),
        updatedAt: ago(30),
      },
      {
        id: "gi-6",
        text: "Chicken",
        completed: false,
        reminderTime: "16:00",
        notes: "For dinner",
        createdAt: ago(20),
        updatedAt: ago(20),
      },
      {
        id: "gi-7",
        text: "Rice",
        completed: false,
        reminderTime: null,
        notes: "",
        createdAt: ago(20),
        updatedAt: ago(20),
      },
      {
        id: "gi-8",
        text: "Tomatoes",
        completed: false,
        reminderTime: null,
        notes: "",
        createdAt: ago(18),
        updatedAt: ago(18),
      },
    ],
  },
  {
    id: "list-coupons-1",
    userId: DEMO_LISTS_USER_ID,
    kind: "coupons",
    title: "Coupon list",
    createdAt: ago(72),
    updatedAt: ago(10),
    items: [
      {
        id: "ci-1",
        text: "$1 off milk — expires Friday",
        completed: false,
        reminderTime: "10:00",
        notes: "Grocery store flyer",
        createdAt: ago(72),
        updatedAt: ago(10),
      },
      {
        id: "ci-2",
        text: "Buy one get one bread",
        completed: false,
        reminderTime: null,
        notes: "",
        createdAt: ago(50),
        updatedAt: ago(50),
      },
    ],
  },
  {
    id: "list-todo-1",
    userId: DEMO_LISTS_USER_ID,
    kind: "todo",
    title: "To-do list",
    createdAt: ago(24),
    updatedAt: ago(1),
    items: [
      {
        id: "ti-1",
        text: "Call the pharmacy",
        completed: false,
        reminderTime: "11:00",
        notes: "",
        createdAt: ago(24),
        updatedAt: ago(1),
      },
      {
        id: "ti-2",
        text: "Water the porch plants",
        completed: true,
        reminderTime: null,
        notes: "",
        createdAt: ago(24),
        updatedAt: ago(3),
      },
      {
        id: "ti-3",
        text: "Write a note to Sarah",
        completed: false,
        reminderTime: "15:30",
        notes: "",
        createdAt: ago(12),
        updatedAt: ago(12),
      },
    ],
  },
  {
    id: "list-custom-1",
    userId: DEMO_LISTS_USER_ID,
    kind: "custom",
    title: "Books to read",
    createdAt: ago(96),
    updatedAt: ago(6),
    items: [
      {
        id: "xi-1",
        text: "The Secret Garden",
        completed: false,
        reminderTime: null,
        notes: "From the library",
        createdAt: ago(96),
        updatedAt: ago(6),
      },
      {
        id: "xi-2",
        text: "A Christmas Carol",
        completed: false,
        reminderTime: null,
        notes: "",
        createdAt: ago(80),
        updatedAt: ago(80),
      },
    ],
  },
];
